apiVersion: apps/v1
kind: Deployment
metadata:
  name: yaml-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yaml-app
  template:
    metadata:
      labels:
        app: yaml-app
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80

